import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import FluidGlass from "@/components/FluidGlass";
import Header from "@/components/Header";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          {/* <div>
            <Link href={"/"}>Home</Link>
            <Link href={"/location"}>지도</Link>
            <Link href={"/contact"}>컨택</Link>
            <Link href={"/ddabong"}>따봉</Link>
          </div> */}
        </header>
        <main>{children}</main>
        <footer></footer>
      </body>
    </html>
  );
}
